name: deploy to ec2
on:
workflow_run:
  workflows: ["build and test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script:
            docker pull kavya00/node-app1:latest
            docker stop node-app1 || true
            docker rm node-app1 || true
            docker run -d --name node-app1 -p 80:3000 kavya00/node-app:latest